spring:
  application:
    name: gestion-app

  datasource:
    url: jdbc:mysql://localhost:3306/techsolution?useSSL=false&serverTimezone=America/Lima
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Vanessa28092006

  jpa:
    hibernate:
      ddl-auto: update   # 'update' mantiene tus datos existentes y crea tablas nuevas si faltan
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true   # para que las consultas SQL se vean legibles en consola

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  controller-advice:
    enabled: false
