spring:
  application:
    name: gestion-app

  datasource:
    url: jdbc:mysql://localhost:3306/techsolution?useSSL=false&serverTimezone=America/Lima
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Vanessa28092006

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  controller-advice:
    enabled: false
